### ISSUE TITLE
Is there a configuration guide?

### ISSUE THREAD

**Issue by thbar** [entur/anshar#156]
Hi there!

Just curious, if I have a couple (2-3) of SIRI (french profile) feeds, is it complicated to configure an anshar node running on a local machine?

How would I declare the sources and their requestor refs?

Do I need a publicly visible machine (or ngrok or similar), since I presume anshar will subscribe for pubsub to these remote SIRI feeds?

Thanks!

**Comment by lassetyr** [comment]
Hi!
You can run anshar as a simple, single-node configuration out-of-the-box - you can either build it yourself, or use the docker-image we publish on [Dockerhub](https://hub.docker.com/r/entur/anshar).

A short usage-guide is available on [Usage.md](https://github.com/entur/anshar/blob/master/Usage.md)

If you want anshar to subscribe to an external feed, you need some sort of public endpoint where the external service can send its data. ngrok will work fine, though it might be overloaded if there is a lot of traffic - I use ngrok frequently for my own testing. For this to work you will need to set your ngrok-url to a property (in [application.properties](https://github.com/entur/anshar/blob/master/src/main/resources/application.properties#L63))
E.g:
```
anshar.inbound.url = https://<...>.ngrok-free.app/anshar/
```

There is an example of a yaml-file that defines subscriptions at https://github.com/entur/anshar/blob/master/src/main/resources/subscriptions-example.yml#L44-L72 
The highlighted lines defines a single subscription for SIRI ET for a given service. A description of the different fields - if they are not self-explanatory - are available at [Subscriptions.md](https://github.com/entur/anshar/blob/master/src/main/resources/Subscriptions.md)

You can also define Request/Response-subscriptions where anshar will send SIRI ServiceRequests to the external service. This will not need an ngrok endpoint since anshar then performs a synchronous request. You can also find an example of this subscription-type in subscriptions-example.yml.

If you then point to your own version of the properties and the subscription yaml-file in your startup-command, you should be ready to go.

Please let me know if you have any issues!

**Comment by thbar** [comment]
Hello @lassetyr! Many thanks, I will try this out at some point, this is perfect, and will get back to you if I have more questions!
