### ISSUE TITLE
How to configure Anshar to subscribe CEN SIRI by Entur?

### ISSUE THREAD

**Issue by dancesWithCycles** [entur/anshar#51]
Hi folks,
Thank you so much for providing and maintaining this repository.

I heart it is possible to subscribe a CEN SIRI VM service using the following address.

https://api.entur.io/realtime/v1/subscribe

The following datasets are looking interesting, as they are offered also in the GTFS-RT format.

VYB	Vy Buss (SE)	
VYX	Vy Express	

From the browser it is obvious that the ENTUR services are working quite well. I get an HTTP response when I send the following GET request.

https://api.entur.io/realtime/v1/rest/vm

Anyhow, I learned that the ```subscriptionMode: SUBSCRIBE``` requires the property ```anshar.inbound.url``` to be set. It is set in this [file](https://github.com/entur/anshar/blob/master/src/main/resources/application.properties).

So, what is the required value for this property? Do I configure something like this.

```
# Required for SUBSCRIBE-subscriptions
anshar.inbound.url = https://api.entur.io/realtime/v1/subscribe
```

Do you mind sharing an example config for Anshar that subscribes a CEN SIRI service like VM?

Cheers!

**Comment by lassetyr** [comment]
Examples of config for subscriptions can be found in the file: https://github.com/entur/anshar/blob/master/src/main/resources/subscriptions-example.yml. All subscriptions listed on the stats-page are configured entirely from this file on startup.

A SIRI publish/subscribe-subscription will instruct the server (in this case our server at Entur) to publish all the requested SIRI-data to an http-endpoint on your side. (I have written a description about the subscription-concepts in https://github.com/entur/anshar/blob/master/Subscription-lifecycle.md.)

Thus, the value for `anshar.inbound.url` needs to be an open endpoint where we (Entur) can post SIRI-data (using HTTP POST) so that it reaches your server.

**Comment by dancesWithCycles** [comment]
Thank you so much for making this crystal clear.

I defined ```anshar.inbound.url``` like this.
```
anshar.inbound.url = http://<ip or domain name>/
```

Is that enough or does the ```anshar.inbound.url``` needs to be defined including a port like this?
```
anshar.inbound.url = http://<ip or domain name>:<port>/
```
Cheers!

**Comment by lassetyr** [comment]
As any other url it is only required to specify the port if it is something _other_ than 80. 

The url will be used as a base-url when [creating the endpoint-address](https://github.com/entur/anshar/blob/master/src/main/java/no/rutebanken/anshar/subscription/SubscriptionSetup.java#L152) for each subscription. The resulting url that our server will post data to is visible on the stats-page of your running application. 

The resulting url then needs to be accessible from anywhere on the internet.

**Comment by dancesWithCycles** [comment]
Cheers mate!
